config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
      
  end
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]

  end
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	
	def self.looks(searches, words)
		if searches == "perfect_match"
			 @book = Book.where("title LIKE ?", "#{words}")
			 
		elsif searches == "forward_match"
			@book = Book.where("title LIKE ?", "#{words}%")
			
		elsif searches == "backword_match"
			@book = Book.where("title LIKE ?", "%#{words}")
		else
			 @book = Book.where("title LIKE ?", "%#{words}%")
		end
	end
	
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
   # foreign_key（FK）には、@user.xxxとした際に「@user.idがfollower_idなのかfollowed_idなのか」を指定します。
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followeds, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attachment :profile_image, destroy: false


  def followed_by?(user)
    passive_relationships.find_by(follower_id: user.id).present?
  end
  
  def self.looks(searches, words)
      
        if searches == "perfect_match"
            @user = User.where("name LIKE ?", "#{words}")
            
        elsif searches == "forward_match"
            @user = User.where("name LIKE ?", "#{words}%")
            
        elsif searches == "backword_match"
            @user = User.where("name LIKE ?", "%#{words}")
            
        else
            @user = User.where("name LIKE ?", "%#{words}%")
        end
  end
   validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
   validates :introduction, length:{maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comments = BookComment.all
    @comment = BookComment.find(params[:id])
    @comment.destroy



  end

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :baria_user, only: [:edit] 

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = @book.user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :favorite)
  end
  
  def baria_user
      @book = Book.find(params[:id])
      @user = @book.user
        unless @user.id == current_user.id
          redirect_to books_path
        end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    follow = current_user.active_relationships.build(followed_id: params[:user_id])
    follow.save
    # Relationship.create(followed_id: params[:user_id], follower_id: current_user.id)
    redirect_back fallback_location: users_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(followed_id: params[:user_id])
    follow.destroy
    #Relationship.find_by(follower_id: params[:user_id], followed_id: current_user.id).destroy
    redirect_back fallback_location: users_path
  end

  

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    
    if @range == "User"
       @users = User.looks(params[:search], params[:word])
    else
       @books = Book.looks(params[:search], params[:word])
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def follows
    user = User.find(params[:id])
    @users = user.followeds
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comment.html.erb
  <% book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(@book.user) do %>
          <%= image_tag('no_image.jpg') %></br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td>
        <%= book_comment.comment %>
      </td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %>
        <% end %>
      </td>
    </tr>
  <% end %>

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render 'book_comments/book_comment', { book_comments: @comment.book.book_comments }) %>")
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'book_comments/book_comment', { book_comments: @comment.book.book_comments }) %>")

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorite_buttons_<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>
        <td>コメント件数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <%= render 'layouts/errors', obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @books %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td><% if user_signed_in? && current_user.id == @book.user_id %></td>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
          <td id="favorite_buttons_<%= @book.id %>">
            <%= render 'favorites/favorite', book: @book %>
          </td>
          <td>コメント件数：<%= @book.book_comments.count %></td>
        </tr>
      </table>
      <table id= "comments_area">
        <%= render 'book_comments/book_comment',book_comments: @book_comments %>
      </table>
          <div class="new-comment">
            <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
              <%= f.text_area :comment, size:'90x5',placeholder: "コメントをここに" %></br>
              <%= f.submit "送信する" %>
            <% end %>
          </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>

        ♥<%= book.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
        ♡<%= book.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/favorites/create.js.erb
$("#favorite_buttons_<%= @book.id %>").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite_buttons_<%= @book.id %>").html("<%= j(render 'favorites/favorite', book: @book )%>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_follow_btn2.html.erb
<% if user.followed_by?(current_user) %>
  <%= link_to "フォローを外す", user_relationships_path(user.id), class: "btn btn-info btn-sm btn-block mb-3 sign_in", method: :delete %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), class: "btn btn-success btn-sm btn-block", method: :post %>
<% end %>

app/views/relationships/_follow_users_btn.html.erb
<% if user.followed_by?(current_user) %>
  <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
<% end %>

app/views/searches/search.html.erb
<div class="container-xl-12">
  <div class='row'>
    <div class='col-md-12'>
      <% if @range == "User" %>
        <h2>Users search for</h2>
        <table class='table'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followeds.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <td></td>
                <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <h2>Books search for</h2>
        <table class='table'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
                <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followeds.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= render 'relationships/follow_users_btn', user: user%></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to  follows_user_path(user) do %>
        <%= user.followeds.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to followers_user_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>

</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% else %>
    <%= render 'relationships/follow_btn2', user: user %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :Name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container-xl-12">
  <div class='row'>
    <div class='col-md-12'>
      <h2>Follower Users</h2>
      <% if @users.empty? %>
        <%= "ユーザはいません" %>
      <% else %>
        <table class='table'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followeds.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <td></td>
                <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class='container-xl-12'>
  <div class='row'>
    <div class='col-md-12'>
      <h2>Follow Users</h2>
      <% if @users.empty? %>
        <%= "ユーザはいません" %>
      <% else %>
        <table class='table'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.followeds.count %></td>
                <td>フォロワー数：<%= user.followers.count %></td>
                <td></td>
                <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    <%= render 'layouts/errors', obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index', users: @users%>
    </div>
  </div>
</div>
 

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>